### ISSUE TITLE
Go Rollups Node

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#101]
## 📚 Context

We are at a point where it is hard to evolve the current Rollups Node because the architecture got too complicated. I wish to rewrite the Node in a simpler monolithic architecture where all the state is centralized into an SQL database. This rewrite will be done in Golang further to improve the maintainability of the next Node version.

Below is the proposed package diagram for the new Rollups Node. All the blue boxes are Go packages that run in the same process. The new architecture is open for discussion and improvements. 

![reader-node](https://github.com/cartesi/rollups-node/assets/8294320/91f497a3-e511-4c57-b88e-28a51695485b)

The main components are the following.

### Repository

The Repository should be the only way to read or write the node state. It is a layer on top of the SQL database. We can replace the SQL database with a more straightforward in-memory database when developing and testing the Node.

### Inputter

The inputter reads the DApp inputs from the blockchain and stores them in the Repository.

### Scheduler

The scheduler gets the inputs from the SQL database, sends them to the Machine Executor, and stores the outputs in the Repository.

### Executor

The Executor will be a high-level interface to execute the inputs. This interface will have two implementations, the Machine and the Dev one. These are analogous to the server manager and the host-server manager, respectively.

### Validator

The Validator decides when to close an epoch, computes the output proofs, stores the proofs in the Repository, and sends the claim to the database.

### Inspect API and GraphQL API

These have the same behavior as the inspect-server and graphql-server.

## 📈 Subtasks

The epic will be divided into the subtasks below. These tasks can be broken down into smaller tasks if necessary. Notice that the SQL repository is one of the last tasks in the list because we might want to change the model during the development of the Node. So, to avoid reworking the SQL schema, we can leave it for later.

- [ ] Add model with documentation (ER Diagram)
- [ ] Implement Debug Interface/health check
- [ ] Implement Inputter
- [ ] Implement Machine Executor: advances
- [ ] Implement Machine Executor: inspects
- [ ] Implement Machine Executor: snapshots
- [ ] Implement Inspect API
- [ ] Implement Dev Executor
- [ ] Port Merkle tree implementation from host-runner
- [ ] Implement Validator: finish epoch decision
- [ ] Implement Validator: generate proofs
- [ ] Implement Validator: submit the claim
- [ ] Implement GraphQL API: by index queries
- [ ] Implement GraphQL API: pagination queries
- [ ] Implement GraphQL API: filters
- [ ] Implement SQL Repository
- [ ] Document the new internal architecture

**Comment by endersonmaia** [comment]
First of all, nice redesign, I really believe things are going to be much simpler that way, and we'll move faster.

One thing I'm missing on the diagram, is where is the box that represents the machine-snapshots? 

How are you planning to deal with them on the `[machine-executor]` box.

**Comment by gligneul** [comment]
Good point, @endersonmaia; I still have to think about this. The MachienExecutor will likely load the snapshots from a filesystem, similar to what we do today. Unlike the current node, the new one should add the reference to the snapshots in the database so the scheduler knows which one it should load. We should avoid adding semantics to the snapshot file name.
