### ISSUE TITLE
Refactor proof generation in host-server-manager

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#11]
## 📚 Context

Proof generation is one of the most complicated logics the host-server-manager has to deal with. In its current implementation, this logic and the data relevant to it are scattered throughout several types and modules, making it difficult to understand the whole picture and forcing us to alter a lot of files when a change is needed. Also, proofs are generated after each input gets processed by the DApp's backend and because of the properties of Merkle trees, they need to be regenerated for each new input, which is wasteful and unnecessary.
The proposal is to solve these issues by:
1. Removing references to proofs, hashes, Merkle trees, and similar abstractions from unrelated types and concentrating them within the `proofs.rs` module, together with the algorithm to generate the proofs.
2. Only generate the proofs when they're needed, which is at the end of an epoch.

This would also have the added benefit of making this code reusable, which might come in handy in the near future.

This issue depends on cartesi/rollups#23 

## ✔️ Solution

Gather all proof-related code in a single module and generate proofs only at an epoch's end.

## 📈 Subtasks

- [ ] Remove the `Proofable` trait
- [ ] Remove proof-related fields from `AdvanceResult`
- [ ] Remove proof-related fields from `Voucher`
- [ ] Remove proof-related fields from `Notice`
- [ ] Remove proof-related fields from `Epoch`
- [ ] Stop generating proofs after processing inputs
- [ ] Encapsulate proof-generating logic inside `proofs.rs`
- [ ] Invert the order sibling hashes are generated

**Comment by gligneul** [comment]
This will be addressed in https://github.com/cartesi/rollups-node/issues/101
