### ISSUE TITLE
CI being triggered when no changes were made on specific files/path

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/rollups-node#114]
## 📚 Context

The [last PR I opened](https://github.com/cartesi/rollups-node/pull/113) was just adding a new workflow to the CI, but I get failed checks on docker build.

Ideally, a CI workflow/job should execute only when relevant files are changed that affect that specific workflow/job.

That way, we save some time (money) on the CI runners and give fast feedback to maintainers and collaborators.

## ✔️ Solution

**A**

A workflow can be triggered only when it has changes to specific directories/files using a [path filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).

Depending on how the current workflow and jobs are implemented, we'd need to extract jobs to separate workflows to use these filters.

**B**

In case we don't want to split jobs, so that the filter can be made on a Job level, we should use an action to check for changes and decide on a latter job if it needs to be executed or not.

Using an action like this one: https://github.com/dorny/paths-filter

## 📈 Subtasks

- [ ] List workflow and jobs that would benefit from this kind of filter/check
- [ ] Get feedback on the best approach
- [ ] Send a PR with the decided approach
