### ISSUE TITLE
Broker module refactor

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#12]
## Context

The `dispatcher`, the `advance-runner` and the `indexer` all use some sort of facade to interact with the broker.
There is some code repetition in the three modules when testing and dealing with the facade.

## Solution

Create a `broker` module to encapsulate the facade.

### Subtasks

- [ ] Create the broker module.
- [ ] Move the dispatcher's facade to the broker module.
- [ ] Release V1 of this refactor to develop.
- [ ] Move the advance-runner's facade to the broker module.
- [ ] Release V2 of this refactor to develop.
- [ ] Move the indexer's facade to the broker module.
- [ ] Release the final version of this refactor to develop.

**Comment by gligneul** [comment]
There will be no Redis in the [new architecture](https://github.com/cartesi/rollups-node/issues/101).
