### ISSUE TITLE
Make dispatcher work with authority-claimer

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#130]
## 📚 Context

For the 1.2 release, the `dispatcher` must stop doing the claims to allow the `authority-claimer` to be the sole responsible for the claims in the Node.

## ✔️ Solution

Remove the claims code from the `dispatcher`.

## 📈 Subtasks

- [ ] Remove deprecated configs
- [ ] Remove claims logic
- [ ] Remove obsolete auxiliary methods and tests

**Comment by gligneul** [comment]
Closed by https://github.com/cartesi/rollups-node/pull/135
