### ISSUE TITLE
 ⬆️ Dependency bump for Node 1.2

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#134]
## 📈 Subtasks

- [x] Update major versions in `Cargo.toml`.
- [x] If an update requires major work, create the corresponding issue.
- [x] Update the dependencies in `Cargo.lock`.
- [x] Update Cartesi dependencies and update README.
- [x] Update Rust base docker image.
- [ ] Verify whether everything is working as expected.

**Comment by gligneul** [comment]
I will not update:
- test containers to 0.15 because of https://github.com/testcontainers/testcontainers-rs/issues/471
- tonic to 0.10 because it requires changes to the state-fold library

I don't plan to create issues for these upgrades because we plan to decommission the Rust node.
