### ISSUE TITLE
Investigate use of DEBIAN_FRONTEND in Docker files

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#15]
## 📚 Context

Currently, there are some docker files that use the DEBIAN_FRONTEND command, however there's discussion online that this is not the right way to do it, and it's actively discouraged

[source 1](https://bobcares.com/blog/debian_frontendnoninteractive-docker/)
[source 2](https://serverfault.com/a/797318)
[source 3](https://github.com/moby/moby/issues/4032#issuecomment-34597177)

## ✔️ Solution

Investigate these claims and change if necessary, or leave as is and document why it's a viable solution.

## 📈 Subtasks

- [ ] Study the use of DEBIAN_FRONTEND in Docker files
- [ ] Document reasons why or why not it's applicable
- [ ] Update the code, if the changes seem necessary

**Comment by gligneul** [comment]
@GMKrieger, is this still happening after the last refactor of the build system?

**Comment by gligneul** [comment]
We are setting it with ARG instead of ENV now: https://github.com/cartesi/rollups-node/blob/v1.1.0/build/Dockerfile#L58
