### ISSUE TITLE
Kickstart cartesi-rollups-cli

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#151]
## 📚 Context

It is hard for the node developer to test the rollups-node because we rely on the rollups-examples infrastructure.

## ✔️ Solution

Having a CLI binary to help manually test the node would be nice.

## 📈 Subtasks

- [x] Create a new Go binary under `cmd`.
- [x] Create the rollups contract bindings in Go.
- [x] Create helper pkg to send transactions using go-ethereum.
- [x] Add command to send inputs.
