### ISSUE TITLE
Add `cartesi-rollups-cli read input`

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#154]
## 📚 Context

See #160

## ✔️ Solution

Following the design of the node GraphQL API, we should have two commands:

### Read a single input

- `cartesi-rollups-cli read input --index N`

This command receives an obligatory parameter index and prints the input of this index.
The input should be printed in a JSON format, like the following:

```
{
    "index": 0,
    "status": "ACCEPTED",
    "msgSender": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
    "timestamp": "1700254651",
    "blockNumber": "79",
    "payload": "0x6869"
}
```

If the input doesn't exist, it returns an error.
```
Error: input not found
```

### Read multiple inputs

- `cartesi-rollups-cli read inputs --first N`

This command reads the first N inputs. The default value for `first` should be 10. Like the previous command, the list of inputs should be printed in a JSON format.

For the time being, we should not worry about pagination.

## 📈 Subtasks

- [ ] Commit GraphQL schema to `api/`
- [ ] Create client bindings of the GraphQL API. I recommend https://github.com/Khan/genqlient.
- [ ] Add command to CLI to print inputs.

**Comment by gligneul** [comment]
I changed the description slightly to have two commands instead of just one.
This reflects best the node GraphQL API and will be easier to implement.
