### ISSUE TITLE
Add `cartesi-rollups-cli read notices`

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#161]
## 📚 Context

See #160

## ✔️ Solution

Following the design of the node GraphQL API, we should have two commands:

### Read a single notice

- `cartesi-rollups-cli read notice --notice-index N --input-index M`

This command receives two obligatory parameters noticeIndex and inputIndex and prints the notice and the input that produced this notice.
The input should be printed in a JSON format, like the following:

```
{
    "index": 0,
    "inputIndex": 0
    "payload": "0x6869",
    "proof":  {
        "inputIndexiWthinEpoch": 0,
        "outputIndexWithinInput": 1,
        "outputHashesRootHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "vouchersEpochRootHash":  "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "noticesEpochRootHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "machineStateHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "outputHashInOutputHashesSiblings": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "outputHashesInEpochSiblings": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "context": "0x31337"
    },
}
```

If the notice doesn't exist, it returns an error.
```
Error: notice not found
```

### Read multiple notices

- `cartesi-rollups-cli read notices --input-index M`

There are 2 possible ways to read multiple notices; `inputIndex` is an optional parameter that defines what is returned.

If there's an `inputIndex`, then the query will get the input first and then a list of the notices produced by that input.

If the `inputIndex` is absent, the query will list all notices, ordered by their index, with no regards to what input produced them.

For the time being, we should not worry about pagination.

## 📈 Subtasks

- [ ] Create the 3 queries
- [ ] Create client bindings of the GraphQL API
- [ ] Create a function that converts the response to the correct types
- [ ] Add command to CLI to print results.
