### ISSUE TITLE
Add `cartesi-rollups-cli read vouchers`

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#164]
## 📚 Context

See #160

## ✔️ Solution

Following the design of the node GraphQL API, we should have two commands:

### Read a single notice

- `cartesi-rollups-cli read voucher --voucher-index N --input-index M`

This command receives two obligatory parameters voucher-index and input-index and prints the voucher and the input that produced this notice.
The data should be printed in a JSON format, like the following:

```
{
    "index": 0,
    "inputIndex": 0
    "payload": "0x6869",
    "destination": "0x1337"
    "proof":  {
        "inputIndexiWthinEpoch": 0,
        "outputIndexWithinInput": 1,
        "outputHashesRootHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "vouchersEpochRootHash":  "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "noticesEpochRootHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "machineStateHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "outputHashInOutputHashesSiblings": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "outputHashesInEpochSiblings": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
        "context": "0x31337"
    },
}
```

If the voucher doesn't exist, it returns an error.
```
Error: voucher not found
```

### Read multiple notices

- `cartesi-rollups-cli read vouchers --input-index M`

There are 2 possible ways to read multiple vouchers; `input-index` is an optional parameter that defines what is returned.

If there's an `input-index`, then the query will get the input first and then a list of the vouchers produced by that input.

If the `input-index` is absent, the query will list all vouchers, ordered by their index, with no regards to what input produced them.

## 📈 Subtasks

- [ ] Create the 3 queries
- [ ] Create client bindings of the GraphQL API
- [ ] Create a function that converts the response to the correct types
- [ ] Add command to CLI to print results.
