### ISSUE TITLE
Create a build step for cartesi machine image

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#173]
## 📚 Context

To fully test the Rollups Node features, we need a dApp's Cartesi Machine snapshot. We're currently building one in our [docker-compose.yml](https://github.com/cartesi/rollups-node/blob/next/build/docker-compose.yml) file, using the very simple [default dApp](https://github.com/cartesi/rollups-node/blob/next/build/machine.Dockerfile#L24) that comes bundled within the Cartesi Machine itself. Although this setup works, the compose file should be used to execute the node, not to run build-related tasks.

## ✔️ Solution

Build the Cartesi Machine snapshot alongside the node image using docker `buildx` instead of `compose`. Both targets can be defined in the same Dockerfile.

## 📈 Subtasks

- [x] Create a new buildx target for the snapshot
- [x] Remove the snapshot's build section from the compose file
- [x] Merge machine.Dockerfile into Dockerfile
- [x] Base the snapshot in the cartesi/machine-emulator:0.15.2 image
