### ISSUE TITLE
Add `description` tag to Config.toml

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#177]
## 📈 Subtasks

- [x] Code `generate.go` to document the functions.
- [x] Integrate with `gendocs` command (`.md` file).
- [x] Add the `description` text in the Config.toml file.
- [x]  Log new environment variables when getting them
