### ISSUE TITLE
Add build stage for devnet creation

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#187]
## 📚 Context

Create a new build stage for devnet by leveraging #149 to bring an instance of anvil up for deploying a CartesiDApp.

## ✔️ Solution

Build a devnet image based on a machine snapshot (see #173).

## 📈 Subtasks

- [x] Add new buildx target for devnet
- [x] Remove deployer from compose
- [x] replace `sunodo/devnet` with `node/devnet` in compose
