### ISSUE TITLE
Add `cartesi-rollups-cli read reports`

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#188]
## 📚 Context

See #160

## ✔️ Solution

Following the design of the node GraphQL API, we should have two commands:

### Read a single report

- `cartesi-rollups-cli read report --report-index N --input-index M`

This command receives two obligatory parameters report-index and input-index and prints the report and the input that produced this report.
The data should be printed in a JSON format, like the following:

```
{
    "index": 0,
    "inputIndex": 0
    "payload": "0x6869",
}
```

If the report doesn't exist, it returns an error.
```
Error: report not found
```

### Read multiple reports

- `cartesi-rollups-cli read reports --input-index M`

There are 2 possible ways to read multiple reports; `input-index` is an optional parameter that defines what is returned.

If there's an `input-index`, then the query will get the input first and then a list of the reports produced by that input.

If the `input-index` is absent, the query will list all reports, ordered by their index, with no regards to what input produced them.

## 📈 Subtasks

- [ ] Create the 3 queries
- [ ] Create client bindings of the GraphQL API
- [ ] Create a function that converts the response to the correct types
- [ ] Add command to CLI to print results.
