### ISSUE TITLE
Multi DApp Authority Claimer

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#197]
## 📚 Context

The claimer only works for a single DApp. So, if we want to run multiple nodes for the same Authority, there will be a race condition when multiple claimers try to send a transaction using the same Ethereum account.

## ✔️ Solution

The simplest solution for this problem is to make the claimer work with multiple DApps.

## 📈 Subtasks

- [x] Add the dapp address to the claims stream payload in the rollups-events [crate](https://github.com/cartesi/rollups-node/blob/main/offchain/rollups-events/src/rollups_claims.rs#L12). We won't be able to use the `decl_broker_stream` anymore.
- [x] Change the [advance runner](https://github.com/cartesi/rollups-node/blob/main/offchain/advance-runner/src/runner.rs#L237) to produce the claims in the correct stream.
- [x] Remove the DApp address from the [claimer config](https://github.com/cartesi/rollups-node/blob/main/offchain/authority-claimer/src/config/cli.rs#L46) and use the DApp address from the claim stream payload.
- [ ] Add a reader mode flag to the advance runner to avoid sending a claim.
- [ ] Add a feature flag to the Go node to not start the claimer. (This is different from the reader mode.)
