### ISSUE TITLE
Metrics for the indexer

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#2]
## 📚 Context

We need to add metrics to the indexer. See cartesi/rollups#17.

## 📈 Subtasks

- [ ] Define what metrics we are going to expose.
- [ ] Implement the metric signaling code.
- [ ] Update the health check to use the `http-server` crate.

**Comment by gligneul** [comment]
Once we migrate to the [new architecture](https://github.com/cartesi/rollups-node/issues/101), retrieving metrics directly from the SQL database will be possible.
