### ISSUE TITLE
Add notices, vouchers and reports to read input

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#209]
## 📚 Context

When first doing #154, the proposed output didn't have the notices, vouchers and reports.

## ✔️ Solution

Add the information to the query using the existing structures for each type. The format of the output JSON will be as following:

```
{
    "index": 0,
    "status": "ACCEPTED",
    "msgSender": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
    "timestamp": "1700254651",
    "blockNumber": "79",
    "payload": "0x6869"
    "notices": [{
      "index": 0,
      "payload": "0x6869",
      "proof":  {
          "inputIndexiWthinEpoch": 0,
          "outputIndexWithinInput": 1,
          "outputHashesRootHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "vouchersEpochRootHash":  "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "noticesEpochRootHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "machineStateHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "outputHashInOutputHashesSiblings": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "outputHashesInEpochSiblings": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "context": "0x31337"
      },
    }],
    "vouchers": [{
      "index": 0,
      "payload": "0x6869",
      "destination": "0x1337"
      "proof":  {
          "inputIndexiWthinEpoch": 0,
          "outputIndexWithinInput": 1,
          "outputHashesRootHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "vouchersEpochRootHash":  "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "noticesEpochRootHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "machineStateHash": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "outputHashInOutputHashesSiblings": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "outputHashesInEpochSiblings": "0xdeadbeefdeadbeefdeadbeefdeadbeef",
          "context": "0x31337"
      },
    }],
    "reports": [{
      "index": 0,
      "payload": "0x6869",
    }]
}
```

## 📈 Subtasks

- [ ] Change the GraphQL query
- [ ] Update the structs
- [ ] Format the output
