### ISSUE TITLE
Create SupervisorService

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#221]
## 📚 Context

As a supervisor, the `cartesi-rollups-node` main role is to start and manage different services. We would like to thoroughly test such important functionality but this effort is currently hindered by its current implementation as we have no easy way of knowing all services have started.

## ✔️ Solution

Use the `Service` abstraction to create a service that executes other services. This would bring the added benefit of opening the opportunity for new types of services to be created as well.

## 📈 Subtasks

- [x] Extract a Service interface from `Service` struct
- [x] Rename the `Service` struct to `CommandService`
- [x] Use a channel to communicate readiness instead of the `Ready()` function
- [ ] Abstract current `services.Run()` logic inside a new `SupervisorService`
