### ISSUE TITLE
Deploy Rollups contracts deterministically on devnet in Go

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#229]
## 📚 Context

Rollups contracts are not begin deployed in a deterministic fashion on `devnet`, which forced us to change the address book used by `cartesi-rollups-cli` to make the relevant addresses match.

We must amend the deployment process so the whole deployment is deterministic.

## ✔️ Solution

~Use a tool (possibly [forge script](https://book.getfoundry.sh/reference/forge/forge-script)) that uses the `CREATE2` opcode to perform the deployment (see [tutorial](https://book.getfoundry.sh/tutorials/create2-tutorial)).~

~Note: Besides being used by rollups-contracts, there's also a mention about using [safe-singleton-factory](https://github.com/safe-global/safe-singleton-factory) at https://github.com/foundry-rs/foundry/issues/2638#issuecomment-1860269617 pointing to https://github.com/bgd-labs/aave-helpers/blob/6cc788d1346e6bcaf8f02878841eb74662c87c17/src/ScriptUtils.sol#L87.~

Use rollups-contracts deployment tools.

## 📈 Subtasks

- [x] Deploy contracts deterministically on `devnet`
- [x] Restore original address book used by `cartesi-rollups-cli`
- [x] Convert shell code to Go

**Comment by tuler** [comment]
Rollups contracts use https://github.com/safe-global/safe-singleton-factory for deterministic deployment to all networks. It also works on foundry.

**Comment by marcelstanley** [comment]
After some experimentation and further consideration, we have decided to backtrack on using foundry-rs and to use rollups-contracts's own deployment script instead. 

There are couple of reasons for that:

- even though we used the same deterministic deployer as rollups-contracts and the right salt, we never got the same deployment addresses for the contracts
- the process became cumbersome and considerably more complex than we expected

Besides all that, the scope of this task has grown to convert all shell code to Go.
