### ISSUE TITLE
Migrate node to cartesi/rollups-node

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#23]
## 📚 Context

As the node unit, we want more control over the git repository.

## ✔️ Solution

Migrate the node codebase to https://github.com/cartesi/rollups-node

## 📈 Subtasks

- [x] Create the new repository
- [x] Move the code to the new repository
- [x] Create milestones in the new repository
- [x] Migrate issues to the new repository
- [x] Remove offchain code from the old repository
- [ ] Remove onchain code from the new repository
