### ISSUE TITLE
Setup HTTP proxy to internal endpoints

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#241]
## 📚 Context
The node exposes several public APIs, namely: graphql, inspect, and rollup (when in host-mode), as well as the /metrics endpoint for `dispatcher` metrics, where each is implemented by a different service inside the node. This setup is not optimal because it requires multiple ports to be exposed, increasing the attack surface and complicating code maintenance.

## ✔️ Solution
Create a reverse proxy inside the node to reroute incoming HTTP requests accordingly, exposing a single port. This will also simplify our plans to transform the current services into Golang modules in the future.

### 📈 Tasks
- [x] Create a proxy for the `/graphql` route
- [x] Create a proxy for the  `/inspect` route
- [x] Create a proxy for the `/rollup` route
- [x] Create a proxy for the `/metrics` route
- [x] Set the service's address to localhost
- [x] Expose a single port
