### ISSUE TITLE
Design database schema changes for output unification

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#242]
## 📚 Context

We should design how the GraphQL will look once we unify vouchers and notices. The deliverable for this issue is the updated GraphQL specification.

## ✔️ Solution

Using PostGraphile, the GraphQL API will auto-generate from the database. So there needs to be an update to the PostgreSQL database and then update the API will update accordingly.

On this moment, we're focusing on the design of the new database and API. The related service and other functionalities will be done in subsequent issues.

## 📈 Subtasks

- [ ] Design new database schema
- [ ] Create a `.sql` file that generates the database
- [ ] Create a script to generate a new db and run PostGraphile

**Comment by marcelstanley** [comment]
Obsoleted in favor of #375
