### ISSUE TITLE
Run node on host or single container

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/rollups-node#26]
## 📚 Context

The current way the off-chain services that compose the cartesi-node solution are released is a container image for each service, and if you deploy each of these services as a separate container (Docker/Kubernetes) everything works just fine.

But when you need to run this directly on the host or inside a single container, you don't have a release available for that.

Why is this problem relevant?

Depending on the environment you need to deploy a cartesi-node, you may have restrictions on how to run multiple services and containers, and make the communication between them.

Although containers are standard, we still need to give support to those that don't use containers.

## ✔️ Solution

We could have a container image release with all the services together.

We could have binary releases without the container, so anyone can deploy this in a "plain old server" VM over a VPS or bare metal.

## 📈 Subtasks

- [x] https://github.com/cartesi/rollups/issues/29
- [ ] Release a single container image with every component for the cartesi-node to run;
- [ ] binary releases at least for `linux/amd64`;
- [ ] systemd init script could be provided together with the Linux binary release;

**Comment by torives** [comment]
This issue has spawned a lot of interesting discussions and issues, but it has become quite confusing. I'll be closing it now, but I've created #80 to tackle its original proposal.
