### ISSUE TITLE
Lint Documentation MD files on CI

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#268]
## 📚 Context

The node docs is comprised of several MDfiles, either manually created or automatically generated.

Sometimes a developer might make changes that are not formatted right and such mistakes go unnoticed.

> This is a follow-up to #266 

## ✔️ Solution

Consider enabling markdown at `.golangci.yml`.

If not possible, add a linter action to CI.

Linters below may be considered:

- https://github.com/DavidAnson/markdownlint
- https://github.com/tcort/markdown-link-check

## 📈 Subtasks

- [x] Add MD linter action to CI
- [x] Add corresponding recipe to Makefile
- [x] Disable linter rules on non-documentation files
