### ISSUE TITLE
Move inspect API to `/api`

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#272]
## 📚 Context

We should move the inspect API from openapi-interfaces to the `api` dir in this repo.

## 📈 Subtasks

- [x] Finish this PR https://github.com/cartesi/openapi-interfaces/pull/7
- [x] Release openapi-interfaces 0.7.0
- [x] Bump openapi-interfaces version in the README 
- [x] Move the inspect file from `./pkg/inspectclient/inspect.yaml` to `./api/openapi/inspect.yaml`.
