### ISSUE TITLE
Add support to reader mode

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#28]
## 📚 Context

The user wants to run the node and only read the state of the blockchain, without sending any claims.

To do this, we decided that a major refactoring is in order, not only to add this support, but also fixing legacy code and patterns that we no longer use while preparing the code to future Cartesi releases.

## ✔️ Solution

The `dispatcher` will lose all claiming logic and be responsible solely for reading the state and updating the machine. It will also need renaming to be more precise to its new use.

A new service called `authority-claimer` will be created, and it will read claims from the broker and make them on the blockchain.

The state-fold, currently another repository, will be imported to the offchain and the old repository will be deprecated. The state-fold will also need refactoring to remove unnecessary code.

## 📈 Subtasks

- [x] cartesi/rollups-node#31 
- [x] cartesi/rollups-node#34 
- [x] cartesi/rollups-node#35 
- [x] cartesi/rollups-node#38 
- [x] cartesi/rollups-node#39 
- [x] cartesi/rollups-node#43 
- [ ] cartesi/rollups-node#40 
- [x] cartesi/rollups-node#41 
- [x] cartesi/rollups-node#42

**Comment by gligneul** [comment]
Since we finished all issues for the 1.2.0 release and only one remains, I will consider this epic as done.
