### ISSUE TITLE
 Dependency bump

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#298]
## 📈 Subtasks

- [x] Update major versions in `Cargo.toml`.
- [x] If an update requires major work, create the corresponding issue.
- [x] Update the dependencies in `Cargo.lock`.
- [x] Update Cartesi dependencies and update README.
- [x] Update Rust base docker image.
- [x] Verify whether everything is working as expected.
