### ISSUE TITLE
Import state-fold to offchain

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#31]
## 📚 Context

State-fold is an auxiliary library that is currently being used only by the dispatcher and it's in another repository in Github.

## ✔️ Solution

Bring the state-fold as another crate inside offchain and have the rest of the offchain code use the new crate.

## 📈 Subtasks

- [ ] Create the state-fold crate
- [ ] Import the state-fold code from the repository with the same name
- [ ] Update necessary code inside the offchain to point to the internal state-fold

**Comment by GMKrieger** [comment]
As discussed on #49, this issue will be postponed indefinitely as we see the need to import the `state-fold` to the node.

**Comment by gligneul** [comment]
Closing it. We can reopen this issue if we need to.
