### ISSUE TITLE
Rewrite Dispatcher in Go

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#320]
## 📚 Context

As part of the initiative to convert the node to Go, we shall reimplement the Dispatcher in Go

## ✔️ Solution

As part of the endeavor, we are also going to remove the dependency from state-fold and implement the necessary features to read from the blockchain instead.

## 📈 Subtasks

- [x] experiment with [subsquid](https://subsquid.io/)
- [x] #329
- [x] #352
- [x] #353
- [ ] #332
- [ ] Sync Input Reader model with 2.0 repository definitions
- [ ] Integrate Input Reader with the node supervisor
- [ ] Subscribe Input Reader to Redis
- [ ] Investigate how claims will be sent to the blockchain and implement that

**Comment by torives** [comment]
I suggest turning this into an epic and creating smaller issues. This is certainly going to take a while to be done.

**Comment by marcelstanley** [comment]
Obsoleted by #375
