### ISSUE TITLE
Remove server-manager interface from host-runner

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#33]
## 📚 Context

The host runner is the service previously named host-server-manager. We should remove the gRPC interface from the host-runner in this issue because it will be refactored in a future issue. This interface doesn't fit this service well because it doesn't have a Cartesi Machine.

## ✔️ Solution

The service should read inputs directly from the broker and send them to the DApp running in the host. Then, it should take the outputs from the host and put them in the broker, as the advance-runner service does. This service should also implement the inspect HTTP API.

## 📈 Subtasks

- [ ] Remove the gRPC interface from host-runner.
- [ ] Get inputs directly from the broker.
- [ ] Write outputs, proofs, and claims to the broker.
- [ ] Provide inspect HTTP interface.
- [ ] Update documentation.
- [ ] Update tests.

**Comment by gligneul** [comment]
Changing the initiative to scalability because this is a step required to scale the node.

**Comment by gligneul** [comment]
We won't do that because we will move to a new architecture in https://github.com/cartesi/rollups-node/issues/101
