### ISSUE TITLE
Create Evm Reader

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#332]
## 📚 Context

The node must continuously read inputs from the `InputBox` contract that are destined to the configured application address.
Such inputs must be made available for the Machine Runner for actual processing by the Cartesi Machine.

## ✔️ Solution

We shall create a new service, `EVMReader`, which will be responsible for reading `Input`s and persisting them in the `Repository`.
The `EVMReader` will consider `Input`s from blocks with configured commitment  status most recent processed block in the `Repository` for proof generation purposes, to be performed by the `Validator`.

## 📈 Subtasks

- [x] Set up basic infrastructure for retrieving inputs and blocks from L1
- [x] Create backend model for handling inputs
- [x] Make sure inputs in gap between past inputs and subscription creation are captured
- [x] Mock database transaction that add inputs and update the most recent finalized block number in the `Repository` 
- [x] Create unit tests
- [X] Accept inputs from multiple applications
- [x] Be resilient against temporary Network glitches when reading L1 state 
- [x] #349
- [x] #456
- [x] #482
- [x] #483
- [x] #486
- [x] #487
- [x] #492
- [x] #506
