### ISSUE TITLE
Create the new authority-claimer service skeleton

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#34]
## 📚 Context

The dispatcher will be separated in two services, one responsible to read the blockchain and update the machine and one responsible for the claims. This issue starts creating the latter, adding a new crate to the workspace.

## ✔️ Solution

Create a new crate named `authority-claimer` on the workspace.

## 📈 Subtasks

- [ ] Create the crate with necessary files to start a mock service
- [ ] Create a broker interface
- [ ] Create a `check-claims` interface
- [ ] Create a `make-claims` interface
- [ ] Add the new service to the appropriate docker initialization
- [ ] Run the service
