### ISSUE TITLE
Add `rollupsmachine` module

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#346]
## 📚 Context

The `rollupsmachine` module provides, through the `RollupsMachine` structure, a way for you to perform structured interactions with the cartesi machine.

You can instantiate a `RollupsMachine` by calling the `rollupsmachine.Load` function.
The `RollupsMachine` structure contains five methods: `Fork`, `Destroy`, `Hash`, `Advance`, and `Inspect`.

You can also call `rollupsmachine.StartServer` and `rollupsmachine.StopServer` to handle the JSON RPC remote server.

## 📈 Subtasks

- [x] Add the `StartServer` and `StopServer` functions.
- [x] Add the `Load` method.
- [x] Add the `RollupsMachine` struct with its methods.
- [x] Test the module.
