### ISSUE TITLE
Create base database migrations

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#347]
## 📚 Context

The new database designed for the output unification will be remade in go and needs setup correctly during startup.

## ✔️ Solution

Add database migrations to the node that guarantee that the schema is consistent when we run the node. This first step will contain the basic tables agreed to be necessary for the continued development of the other services.

## 📈 Subtasks

- [ ] Study and choose a suitable library for the database in Go
- [ ] Implement base migrations for the database
- [ ] Implement fundamental queries for the database
- [ ] Create tests for new repository
