### ISSUE TITLE
 Dependency bump for Rollups 1.4

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#361]
## 📈 Subtasks

- [x] Cartesi
    - [x] Bump Machine Emulator SDK
    - [x] Bump Server Manager
    - [x] Bump Rollups Contracts
    - [x] Update README
- [x] Rust
    - [x] Bump Node version in `Cargo.toml`.
    - [x] Bump major versions in dependencies in `Cargo.toml`.
    - [x] Bump minor/patch dependencies with `cargo update`.
    - [x] Bump Rust version in Docker image.
- [x] Go
    - [x] Bump major versions in dependencies in `go.mod`.
    - [x] Bump minor/patch dependencies with `go get -u all`.
    - [x] Bump Go version in `go.mod`.
    - [x] Bump Go version in Docker image.
- [x] Bump Debian version in Docker image.
- [ ] Verify whether everything is working as expected.
