### ISSUE TITLE
Create Mocked Validator

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#369]
## 📚 Context
Now that we have a general design for the database schema and how the Validator will interact with it, it is time to exercise the component's main logic.

## ✔️ Solution
To create a prototype to validate the Validator's main logic and APIs, mocking the database and the proof-generating code.

## 📈 Subtasks
- [x] Create the necessary types
- [x] Implement the main logic
- [x] Test main logic with mocks
