### ISSUE TITLE
Implement the Merkle proof algorithm

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#395]
## 📚 Context
The Merkle tree is the data structure that generates proofs for the outputs. It currently has three different implementations: 
- [Solidity](https://github.com/cartesi/rollups-contracts/blob/main/contracts/library/LibMerkle32.sol): used by the rollups contracts
- [C](https://github.com/cartesi/machine-emulator-tools/blob/main/sys-utils/libcmt/src/merkle.c): used inside the Cartesi Machine
- [Rust](https://github.com/cartesi/rollups-node/blob/main/offchain/host-runner/src/merkle_tree/complete.rs): used by the Node v1.x

The original plan for Node v2 was to port the Rust implementation to Go. This was later abandoned as the Rust implementation was deeply intertwined with the old way of generating proofs (dividing the original keccak256 hash into four 64-bit pieces and creating a Merkle tree with them), overcomplicating it.

## ✔️ Solution
The Node's use case for Merkle proofs is straightforward: it only needs to generate proofs at an epoch's end. By then, we already have all the outputs available and can calculate the root hash and the sibling arrays. This only needs to be done once, as there won't be any new outputs for that epoch that would require recalculating it.

Therefore, we can design a more efficient algorithm than a complete, generic Merkle tree data structure that wouldn't fit our current needs as well. The algorithm in question is very similar to the one currently implemented in Solidity.

## 📈 Subtasks
- [x] Write the algorithm in golang
- [x] Test it against the Solidity implementation
- [x] Test it against the C implementation
