### ISSUE TITLE
Remove claims from the dispatcher

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#40]
## 📚 Context

With the `authority-claimer` responsible for the claims, this section of the `dispatcher` code will be deprecated. The service that remains will need only to read the state and keep the machine updated.

## ✔️ Solution

Remove the redundant code from the `dispatcher`.

## 📈 Subtasks

- [x] Remove main loop calls
- [x] Remove blockchain driver
- [x] Remove obsolete auxiliary methods and tests
- [x] Rename `dispatcher` to a more appropriate name

**Comment by gligneul** [comment]
After discussing with @GMKrieger, we decided it is not worth moving forward with this issue because focusing our effort on the Go node is more important.
