### ISSUE TITLE
Bump Rust version to 1.78.0

### ISSUE THREAD

**Issue by fmoura** [cartesi/rollups-node#400]
## 📈 Subtasks

- [ ] Rust
    - [ ] Bump Rust version in Docker image.
    - [ ] Bump Rust version in AuthorityClaimer.
- [ ] Verify whether everything is working as expected.
