### ISSUE TITLE
Eliminate duplicate Devnet Config code among tests

### ISSUE THREAD

**Issue by fmoura** [cartesi/rollups-node#417]
## 📚 Context

More than one tests that uses Devnet, have the same multiline code that configure Devnet. We need to eliminate duplicate code.

## ✔️ Solution

Make a default function that builds this default config, eliminating duplicate code

## 📈 Subtasks

- [ ] Make default config for running only Devnet
- [ ] Refactor ehtutils tests
- [ ] Refactor machine tests

**Comment by vfusco** [comment]
Does not make sense anymore.
