### ISSUE TITLE
Convert devnet-based automated tests to use `no mining` mode

### ISSUE THREAD

**Issue by fmoura** [cartesi/rollups-node#418]
## 📚 Context

Some tests uses Devnet on default automine mode. But tests will benefit of a more controlled and predicted way of handling inputs, outputs and associated hashes 

## ✔️ Solution

To refactor the tests , disabling the default Devnet `auto mine` and  adding "mine" commands to fine tune block generation (see #415)

## 📈 Subtasks

- [ ] Refactor ethutil tests
- [ ] Refactor machine tests
- [ ] Refactor echo-test

**Comment by marcelstanley** [comment]
ethutil tests covered at eddf0a06dbceee66648f0a94719fa739013123f7

**Comment by vfusco** [comment]
Deprecated. If at some point we need a test with managed devnet mining it will be handled on a specific issue.
