### ISSUE TITLE
Normalize naming of boolean configuration parameters 

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#427]
## 📚 Context

Configuration parameters of type `bool` are not normalized (see [config.md for 2.0](https://github.com/cartesi/rollups-node/blob/next/2.0/docs/config.md))

## ✔️ Solution

As a suggestion by @endersonmaia captured at https://github.com/cartesi/rollups-node/issues/426#issuecomment-2127655208, we could use suffixes `ENABLED`/`DISABLED` for all `bool` arguments to imply state and normalize their meaning.

## 📈 Subtasks

- [x] Evaluate possible solutions along with the one listed above
- [x] Apply changes and update docs
- [x] Execute unit tests
