### ISSUE TITLE
Document authority-claimer

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#43]
## 📚 Context

The new `authority-claimer` service needs a README, as well as pertinent comments throughout the code.

## ✔️ Solution

Write a readme for the service and check to see if the code is readable.

## 📈 Subtasks

- [x] Write a README
- [x] Read the code
- [x] Comment the code as needed
- [x] Update the offchain README

**Comment by gligneul** [comment]
Closed by https://github.com/cartesi/rollups-node/pull/143
