### ISSUE TITLE
Generate proofs

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#446]
## 📚 Context
With the ability to generate Merkle proofs (#395), we must now use it to create the `Proof` struct (a.k.a. OutputValidityProof) for each of the outputs within an epoch.

As a reference, [this](https://github.com/cartesi/rollups-node/blob/aff7c56bd0ad0bc058346b436fd1c559c7827ad6/offchain/host-runner/src/grpc/server_manager.rs#L667) is the old version of the same code in Rust, used in the host-runner.

## ✔️ Solution
TBD

## 📈 Subtasks
- [ ] Obtain the root hash for all outputs within an input
- [ ] Obtain the root hash for all outputs within an epoch
- [ ] Create the `Proof` struct for all outputs
- [ ] Create the `Claim`

**Comment by torives** [comment]
Replaced by #553
