### ISSUE TITLE
Update readerclient pkg

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#459]
## 📚 Context

The `readerclient` is a pkg designed to assist the cli by manipulating data and connecting to the GraphQL client to fetch desired information.

It works using by a client (https://github.com/Khan/genqlient) that creates a connecting interface and a series of getter functions based on a GraphQL API (generated by PostGraphile) and graphql queries, which are written by hand.

As the API evolves, so too the readerclient needs to adapt, the API generated by PostGraphile updated and the queries re-written.

## ✔️ Solution

First, the new API model needs to be generated using PostGraphile. This is as simple as enabling a flag in PostGraphile.

After that, the queries need to be re-written to properly get the information needed with the new names and signatures.

Lastly, some adaptations are needed on the final models and the wat the data is handled before being sent back to the cli.

## 📈 Subtasks

- [ ] Generate new GraphQL API
- [ ] Rewrite GraphQL queries
- [ ] Adapt client methods for the new data

**Comment by GMKrieger** [comment]
This issue is deprecated, as the cli will undergo major changes for 2.0.0 that need to be aligned with the team.
