### ISSUE TITLE
Test upgrade procedure for 1.5 on honeypot

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#462]
## 📚 Context

Honeypot is the only application owned by Cartesi which is deployed to mainnet and runs [v1.3.1](https://github.com/cartesi/rollups-node/releases/tag/v1.3.1).

It's important that we verify that the upgrade procedure devised for the forthcoming release `v.1.5` at #461 is tested on such application in order to prevent any issues.

## ✔️ Solution

We shall test the procedure defined at #461 and make sure it works on a testnet.

## 📈 Subtasks

- [ ] Test upgrade procedure on devnet
- [ ] Replicate upgrade procedure on a testnet. The results must be kept on record, showing evidence the application funds were kept intact

## ✅ Definition of Done

- [ ] Update procedure works as expected, the application state is kept intact and no funds are lost in the process
- [ ] Test results are documented

**Comment by endersonmaia** [comment]
For honeypot@mainnet, keep in mind that it was kept on 1.3.x version because it was necessary to generate a new snapshot (templateHash) when moving to 1.4.x, so the same would be needed when moving to 1.5.x.
