### ISSUE TITLE
Add `nodemachine` module

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#466]
## 📚 Context

The `nodemachine.NodeMachine` structure wraps a `rollupsmachine.RollupsMachine`.
It does two main things:
- Allows advance and inspect requests to run concurrently.
- Limits the number of concurrent inspects.

## 📈 Subtasks

- [x] Implement a priority mutex.
- [x]  Implement the `Advance` and `Inspect` methods.
- [ ] Test the module.

**Comment by vfusco** [comment]
Test will be done on another issue
