### ISSUE TITLE
Update dependencies for v1.5.0

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#472]
## 📈 Subtasks

- [x] Rust
    - [x] Bump Node version in `Cargo.toml`.
    - [x] Bump Rust version in Docker image.
- [x] Go
    - [x] Bump major versions in dependencies in `go.mod`.
    - [x] Bump minor/patch dependencies with `go get -u all`.
    - [x] Bump Go version in `go.mod`.
    - [x] Bump Go version in Docker image.
- [ ] Verify whether everything is working as expected.
