### ISSUE TITLE
Design multi-dapp database

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#477]
## 📚 Context

Future Node releases will support multiple dapps running simultaneously, and the database needs to be able to handle it. Current database design is predicated on a single dapp running on the Node at a time.

The database needs to be designed for such, and be able to run properly no matter how many dapps.

## ✔️ Solution

First and foremost, we need to gather information, internally and from other teams, about what information is available to us, and what they expect for their projects.

Then, we need to study which information is dapp specific data and data that is used by all dapps.

Finally, the database must be designed so that the dapps can run concurrently, as efficiently as possible, preferably in a single schema.

## 📈 Subtasks

- [x] Discuss with other Cartesi members
- [x] Study the information
- [x] Design the database
- [x] Run through the team and check if everyone agrees
