### ISSUE TITLE
Implement multi-dapp database

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#478]
## 📚 Context

The database designed on #477 needs to be implemented over the previous design.

We need to make sure that all functions work as intended, the tests run ok, and that it works with one dapp or multiple dapps.

## ✔️ Solution

For the update procedure, we should do as following, in order:
- Update the migrations
- Update the repository functions
- Update the tests

The updated migrations will guarantee the database is being setup correctly; the functions will need to change to the new database design; finally, the tests will guarantee the integrity of the code.

## 📈 Subtasks

- [x] Update the migrations
- [x] Update the repository functions
- [x] Update the tests

**Comment by marcelstanley** [comment]
Done at #511
