### ISSUE TITLE
Create mocked Claim Publisher

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#479]
## 📚 Context
The `claim-publisher` is the penultimate step on the node cycle. It collects the claim information from the database, then manipulates it to send it to Rust component, the Dispatcher, that will then send it to the blockchain.

It is imperative that the Claim Publisher follows the rules defined on the previous versions of the Node (1.x.x) for interacting with Redis, as the Claimer component is legacy from that versions.

## ✔️ Solution
Create a new sub-package of `node` called `claimpublisher` with two sequential tasks: collect claim information from the database, send it to Redis and the listen to the Redis for the update when the claim is mined by the Rust Claimer.

1. Collect claim information from the database
The validator will process inputs and publish the claims and proofs on the database at the end of every epoch. The Claim Publisher needs gather this information after its published, guaranteeing it's not getting anything duplicate or, in case there's no claim, not getting anything at all.

2. Send it to Redis
The information needs to be treated so that it matches the specs of the Rust Claimer, and then posted on Redis for publication on the chain.

3. Listen to Claimer response
The Claimer will put on Redis the information when the claim is mined, and the Claim Publisher needs to catch this information and update the database.

## 📈 Subtasks
- [ ] Create the necessary types
- [ ] Create a mock repository interface
- [ ] Implement the main logic
- [ ] Test the main logic with mocks

**Comment by vfusco** [comment]
This old and deprecated. We have a `claimer` module now. Any issues related to that should be specific and referencing it.
