### ISSUE TITLE
Implement the Claim Publisher algorithm

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#481]
## 📚 Context
After the successful mock of the Claim Publisher (#479), the code needs to be implemented to correctly execute the service.

The validity of the functionality needs to be checked against the Rust service, who needs to correctly publish the Claim on the chain.

## ✔️ Solution
The Claim Publisher needs to be called at the end of every epoch, after the validator has run. It needs to correctly identify if there's a new claim, get the information from the repository, model it in the way the Rust service expects and put it on Redis.

After that, it will wait until it's called again at the end of the next epoch.

## 📈 Subtasks
- [ ] Check if there's a new claim
- [ ] Call the repository (method created on #480)
- [ ] Put it on Redis

**Comment by vfusco** [comment]
The claimer was reimplemented in Go
