### ISSUE TITLE
Add retry at Input Reader interactions with EVM

### ISSUE THREAD

**Issue by fmoura** [cartesi/rollups-node#482]
## 📚 Context

We Noticed that in some environments a EVM Events subscription disconnections is kind of frequent

## ✔️ Solution

At connection errors, Input Reader should try reconnecting to EVM . If a few ( configurable ) retries fail, then raise the error

## 📈 Subtasks

- [ ] Check if is there some library that could help managing disconnection and errors
- [ ] Do a EthClient delegate to handle this 
- [ ] Do a InputSource delegate to handle this

**Comment by fmoura** [comment]
Included in #332
