### ISSUE TITLE
Update authority-claimer to read from repository

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#493]
## 📚 Context
With the update in the Node architecture, Redis has become deprecated as all information circulates through the repository. The way the contracts handle claims also changed, with a new event being emitted when the claim is submitted and accepted.

Both of this changes change the way the authority-claimer needs to handle claims, and the code needs to be updated to handle these demands.

## ✔️ Solution
The authority-claimer in Rust will no longer get the information from the Broker and Redis, and retrieve the information directly from the database. A repository interface and methods need to be implemented on the claimer for it to correctly operate. The claimer will also need to update the database once the claim is submitted, correctly signaling that it has done its job.

The connection with Redis needs to be deprecated, and its functionalities removed.

## 📈 Subtasks
- [ ] Created repository interface
- [ ] Update claimer algorithm
- [ ] Remove deprecated code
