### ISSUE TITLE
Update EVM Reader to read claim status

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#494]
## 📚 Context
The contract now emits an event that signals that a claim has been accepted, and the Node needs to catch this event and update the data on the repository.

The input reader currently is the service that reads the chain information block by block, and so, it needs to be updated to correctly identify this claim acceptance events and update the repository.

## ✔️ Solution
The input reader already is responsible for reading the chain, and gets every new block it produces. Now, it will check not only for new inputs, but for claim accepted events. Whenever a block contains this event, the reader needs to update the claim status on the database.

To match its new functionality, the input reader should be renamed to evm reader.

## 📈 Subtasks
- [ ] Created new repository method
- [ ] Update reader to detect claim accepted events
- [ ] Update algorithm to correctly update when a new claim event arrives

**Comment by fmoura** [comment]
Right now the the Claim model at 2.0 Spec, dos not have a way of narrowing down on which block a claim was published to serve as a starting point to check for ClaimAcceptance event. Maybe it is just an optmization, but ould be nice to have something so the component do not keep re-checking the same blocks it already checked.

**Comment by vfusco** [comment]
Already implemented on the new claimer
