### ISSUE TITLE
[EVM Reader] Standardize Retry Policy use

### ISSUE THREAD

**Issue by fmoura** [cartesi/rollups-node#526]
## 📚 Context

Retry policy is only being used on calls to the Blockchain thought EthClient. This same policy should be applied to every possible request and Databases calls as well

## ✔️ Solution

Apply Retry Policy on EthClient and Database connection and also on top of calls to the Database

## 📈 Subtasks

- [ ] Check the need and apply Retry Policy on top of EthClient creation
- [ ] Apply Retry Policy on Database connection
- [ ] Apply Retry Policy on Database calls

**Comment by vfusco** [comment]
This is old, but the ones that make sense are already done on `next/2.0`.
