### ISSUE TITLE
Implement application-specific rollups-claims streams

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#538]
## 📚 Context

Claims created by a node are sent to a `rollups-claims` stream and further processed by the authority-claimer, which works well in a regular rollups-node

A rollups-node running the [experimental sunodo validator mode](https://github.com/cartesi/rollups-node/blob/main/docs/config.md#cartesi_experimental_sunodo_validator_enabled) on the sunodo designated provider will point to an external standalone authority-claimer, which expects to handle claims from multiple applications via a single `rollups-claims` stream.
Such scenario is not currently supported. 

However, we could extend the current rollups-node capabilities to allow for that, so that a standalone authority-claimer could be configured to support publishing claims for multiple applications running on the same chain.

This would address the case described at #522.

## ✔️ Solution

1. Create application-specific `rollups-claims` streams, identified by the application address and the chain-id, the same way its `rollups-inputs` and `rollups-outputs` counterparts
2. Extend the authority-claimer so it can handle multiple `rollups-claims` streams simultaneously when running on standalone mode

## 📈 Subtasks

- [ ] advance-runner
  - [ ] add support to application-specific `rollups-claims` streams
  - [ ] improve tests
- [ ] authority-claimer
  - [ ] add support to application-specific `rollups-claims` streams
  - [ ] allow configuration of the applications to be managed by the claimer when running on standalone mode
  - [ ] update command line program
  - [ ] improve tests
