### ISSUE TITLE
Improve logging when interacting with `server-manager`

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#541]
## 📚 Context

Errors issued by the `server-manager` are currently being treated as warnings even in irrecoverable scenarios (re "session is tainted"). See [sample node logs from debug session](https://github.com/user-attachments/files/16428957/debug-session-tained-server-manager.txt).

Such cases should be treated as errors and both the `advance-runner` and `inspect-server` should log them as such after such situations occur. These irrecoverable scenarios should be precisely logged that as well.

Additionally, the log levels used by both the `advance-runner` and `inspect-server` are not accurate and should be reviewed as well.

## ✔️ Solution

Update the `advance-runner` and `inspect-server` components to treat and log `server-manager` errors properly.

## 📈 Subtasks

- [x] `advance-runner`
  - [x] update handling of `server-manager` errors
  - [x] review all log levels
- [x] `inspect-server`
  - [x] update handling of `server-manager` errors
  - [x] review all log levels
- [x] Check for other necessary updates

**Comment by marcelstanley** [comment]
Amended description. Irrecoverable errors will be treated at #547
