### ISSUE TITLE
Implement the multi-dapp Validator

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#553]
## 📚 Context
With the addition of multi-app support for the upcoming 2.0 version, the original validator solution proposed in #359 and partially implemented in #348 and #369 (not merged) must be adapted.

Aside from the logic of handling multiple applications instead of one, the biggest change is that epoch finalization will no longer happen inside the Validator but will be handled by the Evm Reader (#545).

Depends on  #395.
## ✔️ Solution
Abstract the claim and proof generating code in a single function to be called once for all app’s closed epochs which had all its inputs processed by the Cartesi Machine. All epoch handling code will be removed and the `ValidatorRepository` interface will be rewritten to reflect Validator’s new needs (#549).
## 📈 Subtasks
- [x] Define the new `ValidatorRepository` interface
- [x] Adapt validator’s logic for multi-app
- [x] Write unit tests
