### ISSUE TITLE
[CONTRACTS] Upgrade Node 2.0 contracts to rollups contracts 2.0.0 RC 6

### ISSUE THREAD

**Issue by fmoura** [cartesi/rollups-node#555]
## 📚 Context

Rollups team released contracts 2.0.0 RC 6. New tasks are in need of these upcoming contracts

## ✔️ Solution

Upgrade `rollups-contracts` submodules and do the necessary code update.

## 📈 Subtasks

- [x] Update `rollups-contracts-submodules`
- [x] Update Node 2.0 code
- [x] Check Devnet generation
