### ISSUE TITLE
Bump dependencies for 1.5.1

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#563]
## 📈 Subtasks

- [ ] Rust
    - [ ] Bump Node version in `Cargo.toml`.
- [ ] Go
    - [ ] Bump major versions in dependencies in `go.mod`.
    - [ ] Bump minor/patch dependencies with `go get -u all`.
    - [ ] Bump Go version in `go.mod`.
    - [ ] Bump Go version in Docker image.
- [ ] Bump Debian version in Docker image.
- [ ] Verify whether everything is working as expected.

**Comment by vfusco** [comment]
1.6 will not be released
