### ISSUE TITLE
[CLI] Move Application contract deployment from Devnet generation to CLI

### ISSUE THREAD

**Issue by fmoura** [cartesi/rollups-node#570]
## 📚 Context

Once Node is Multi Application , a Default Application do not make sense. Also besides the Application Contract being deployed, Applications must be registered 

## ✔️ Solution

Move the Application Contract deployment code to CLI , so Application Contract Deployment and Application Management can reside and be used on Multi Application Devnet test scenarios 

## 📈 Subtasks

- [ ] Remove Application Contract Deployment from Devnet Generation
- [ ] Externalize contracts addresses generated during Devnet build
- [ ] Add Application Contract deployment command to CLI

**Comment by vfusco** [comment]
done
