### ISSUE TITLE
Rewrite host-runner

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#68]
## 📚 Context

Today the host-server manager is more complex than it needs to be. It communicates with the advance-runner using the server-manager gRPC interface, which unnecessarily complicates its implementation.

Since we are discussing a new development language for the node, this is a great opportunity to test it as this is a self-contained service that would not interfere with the node's normal behavior.

## ✔️ Solution

Remove the gRPC API and instead read inputs and write outputs directly to the database.

## 📈 Subtasks

- [ ] Define tooling and create a barebones project
- [ ] Configure the Environment variables
- [ ] Configure log
- [ ] Implement the health-check
- [ ] Connect to the Postgres DB
- [ ] Implement the Rollups HTTP API
- [ ] Implement the Inspect State HTTP API
- [ ] Generate proofs
- [ ] Update the Dockerfile
- [ ] Write tests

**Comment by gligneul** [comment]
Will be done in https://github.com/cartesi/rollups-node/issues/101
