### ISSUE TITLE
Standardize node config

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#7]
## 📚 Context

Each service has its own way of getting config values.

## ✔️ Solution

Change the config to be standardized across all services.

## 📈 Subtasks

- [ ] Migrate from struct-opt to clap. Clap merged the struct-opt features and made it deprecated.
- [ ] Improve the documentation and default values of the config variables. In particular, we should improve the documentation of variables with abbreviations (e.g. HC, RD, SC, and TX).
- [ ] Move all config to a single file in the root of each crate. Some crates have their configs hidden in the middle of the code.
- [ ] Standardize the error handling in the config. I'm in favor of using expect instead of errors because config errors are not recoverable anyway.

**Comment by gligneul** [comment]
Replaced by https://github.com/cartesi/rollups-node/issues/88
