### ISSUE TITLE
Provide completion status in GraphQL API

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#73]
## 📚 Context

A rollups input can have several statuses. It might be unprocessed, accepted, rejected, or have other error status. See https://github.com/cartesi/grpc-interfaces/blob/main/server-manager.proto#L177

Currently, the advance-runner ignores the status and only logs in a trace message when the input is not accepted.  So it is hard for the node user to understand when an input is not processed as expected.

## ✔️ Solution

We should provide the input status in the GraphQL API as another field for the rollups input.
The status should be an enum, including unprocessed, accepted, or rejected, with the reasons in https://github.com/cartesi/grpc-interfaces/blob/main/server-manager.proto#L177.

## 📈 Subtasks

- [ ] Add input status do rollups-events as an output
- [ ] Emit input status in the advance runner
- [ ] Save input status in the indexer
- [ ] Add input status to the Postgres schema
- [ ] Add input status to the GraphQL interface
