### ISSUE TITLE
Create the base Go project

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#91]
## 📚 Context

This is the starting point for implementing #80, with the goal of exercising its main functions and APIs. The `graphql-server` was chosen as the first service for being simpler and therefore easier to test.

## 📈 Subtasks

- [x] Handle the execution mode CLI parameter
- [x] Forward the environment variables
- [x] Start `graphql-server`
- [x] Handle stdout and stderr
