### ISSUE TITLE
Dependency bump for release 1.1.0

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#99]
## 📈 Subtasks

- [ ] Update major versions in `Cargo.toml`.
- [ ] If an update requires major work, create the corresponding issue.
- [ ] Update the dependencies in `Cargo.lock`.
- [ ] Update Cartesi dependencies and update README.
- [ ] Update Rust base docker image.
- [ ] Verify whether everything is working as expected.
